# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55866f0dac4c894e07b863b4739a5e4047ef1a1caeab98e85413faa4022110d7c0b6db6fce77a61887c1cc4769891060efe6339ed7d3a67333c7921d34caf629

test:
  secret_key_base: 062cb258951cf68954a10014b6dcdac69565fe8d826b9e8d22e411a9d1f8a992c6bd0fe4c76a336b111b6687acb49df9c6d2e7de51d685bd087d00e20b91797c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
